### ISSUE TITLE
Status should be choice

### ISSUE THREAD

**Issue by jnayak1** [cavdailyonline/thecavalierdani#5]
[Status](https://github.com/leodomingo/thecavalierdani/blob/master/mysite/unicorn/models.py#L43) should be choice field to make it easier for filtering/searching/validation IMO.

**Comment by leodomingo** [comment]
Yeah, that was a half fulfilled requirement on my part. I'm still brainstorming as to which options I should actually make available

**Comment by jnayak1** [comment]
Max and I were discussing this and it looks like the way to do this is to keep it as a CharField and then add validation to forms/api

**Comment by leodomingo** [comment]
Why a Charfield? There will be basically 3 different statuses available

**Comment by ml3ha** [comment]
I was discussing the school field with Jesse, perhaps he got that mixed up?

**Comment by leodomingo** [comment]
If so than that works fine, but even then we have a set amount of schools here

**Comment by jnayak1** [comment]
It looks like how people do it, they use validators on their api/forms instead of on their model/database
